//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flextech_web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Date { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Count { get; set; }
        public string Store { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
