//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flextech_web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptItem
    {
        public int ID { get; set; }
        public Nullable<int> Name { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ReceiptID { get; set; }
    }
}
